
# Generated by CodiumAI
from doubleLL_v2 import DoublyLinkedList



class TestDoublyLinkedList:

    # Test that a node is successfully removed from the doubly linked list
    def test_remove_node(self):
        # Create a new doubly linked list
        dll = DoublyLinkedList()

        # Append nodes to the list
        dll.append(1)
        dll.append(2)
        dll.append(3)

        # Remove the second node from the list
        dll.remove(1)

        # Check that the second node is no longer in the list
        cur = dll.head
        while cur:
            assert cur.data != 2
            cur = cur.next

